version: "2"
checks:
  similar-code:
    config:
      threshold: 60
exclude_patterns:
- "**/Pods/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*Spec.swift"
- "**/*.test.js"
- "**/*.config.js"
