platform :ios, '11.0'

target 'EthersTests' do
  pod 'Quick', '~> 1.3', inhibit_warnings: true
  pod 'Nimble', '~> 7.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
