platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Telepath' do
  pod 'base64url', '~> 1.0'
  pod 'Socket.IO-Client-Swift', '~> 13.3'

  # Workaround for https://github.com/jedisct1/swift-sodium/issues/155:
  pod 'Sodium', git: 'https://github.com/jedisct1/swift-sodium.git', branch: 'master'

  target 'TelepathTests' do
    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.1'
    pod 'STRegex', '~> 2.0'
    pod 'SwiftLint'
    pod 'Mockingjay', git: 'https://github.com/metaltoad/Mockingjay.git', branch: 'mt-swift4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
