platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Telepath' do
  podspec

  target 'TelepathTests' do
    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.1'
    pod 'STRegex', '~> 1.1'
    pod 'SwiftLint', '0.21.0'
    pod 'Mockingjay', git: 'https://github.com/metaltoad/Mockingjay.git', branch: 'mt-swift4'
  end
end
