platform :ios, '11.0'

target 'Cogito' do
  use_frameworks!
  inhibit_all_warnings!

  # Workaround for https://github.com/jedisct1/swift-sodium/issues/155:
  pod 'Sodium', git: 'https://github.com/jedisct1/swift-sodium.git', branch: 'master'

  pod 'ReSwift', '~> 4.0'
  pod 'ReSwiftThunk', '~> 1.0'
  pod 'Geth', '~> 1.7.1'
  pod 'BigInt', '~> 3.0'
  pod 'SwiftLint', '0.27.0'
  pod 'ReRxSwift', '~> 2.0'
  pod 'KeychainAccess', '~> 3.1'
  pod 'QRCodeReader.swift', '~> 10.0'
  pod 'Telepath', :path => '../telepath-ios'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'JWTDecode', '~> 2.1'
  pod 'FontAwesome.swift', '~> 1.3'
  pod 'RichString', :git => 'https://github.com/svdo/swift-RichString', branch: 'master'
  pod 'Toast-Swift', '~> 4.0'
  pod 'base64url', '~> 1.0'

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'

  target 'CogitoTests' do
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
    pod 'Mockingjay', '~> 2.0'
    pod 'URITemplate'
  end

end
