platform :ios, '11.0'

target 'Cogito' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Sodium', '~> 0.8'
  pod 'ReSwift', '~> 4.0'
  pod 'ReSwiftThunk', '~> 1.0'
  pod 'BigInt', '~> 3.0'
  pod 'SwiftLint', '0.27.0'
  pod 'ReRxSwift', '~> 2.0'
  pod 'KeychainAccess', '~> 3.1'
  pod 'QRCodeReader.swift', '~> 10.0'
  pod 'Telepath', :path => '../telepath-ios'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'JWTDecode', '~> 2.1'
  pod 'FontAwesome.swift', '~> 1.3'
  pod 'RichString', '~> 2.2'
  pod 'Toast-Swift', '~> 4.0'
  pod 'base64url', '~> 1.0'

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'

  target 'CogitoTests' do
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
    pod 'Mockingjay', '~> 2.0'
    pod 'URITemplate'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
