platform :ios, '11.0'

target 'Telepath Demo App' do
    use_frameworks!

    pod 'Telepath', :path => '../telepath-ios'

    # Workaround for https://github.com/jedisct1/swift-sodium/issues/155:
    pod 'Sodium', git: 'https://github.com/jedisct1/swift-sodium.git', branch: 'master'
end
